POST https://localhost:5051/basket
Content-Type: application/json

{
  "Cart": {
    "userName": "testUser2",
    "items": [
      {
        "productName": "Sample Product",
        "quantity": 2,
        "price": 10.5
      },
      {
        "productName": "Another Product",
        "quantity": 1,
        "price": 20.0
      }
    ]
  }
}