
services:
  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
    
  messagebroker:
    image: rabbitmq:management
    
  orderdb:
    image: mcr.microsoft.com/mssql/server
    
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
      
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
   
  ordering.api:
    image: orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
volumes:
  postgres_catalog:
  postgres_basket: